### ISSUE TITLE
When using Cucumber runner, my tests always launch in TestNg instead of junit

### ISSUE THREAD

**Issue by CucumberUserR** [mkolisnyk/cucumber-reports#199]
Hello ,

I am trying to use ExtendedCucumberOptions in my junit-cucumber test

i have the below imports

import com.github.mkolisnyk.cucumber.runner.ExtendedCucumber;
import com.github.mkolisnyk.cucumber.runner.ExtendedCucumberOptions;

POM : 
 <dependency>
            <groupId>com.github.mkolisnyk</groupId>
            <artifactId>cucumber-runner</artifactId>
            <version>1.3.3</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.github.mkolisnyk</groupId>
            <artifactId>cucumber-report-generator</artifactId>
            <version>1.3.3</version>
            <scope>test</scope>
        </dependency>
  <dependency>
			<groupId>info.cukes</groupId>
			<artifactId>cucumber-junit</artifactId>
			<version>1.2.5</version>
		</dependency>
		<dependency>
			<groupId>info.cukes</groupId>
			<artifactId>cucumber-java</artifactId>
			<version>1.2.5</version>
		</dependency>
		<dependency>
            <groupId>info.cukes</groupId>
            <artifactId>cucumber-core</artifactId>
            <version>1.2.5</version>
            <scope>test</scope>
        </dependency>

But when I run my Junit-Cucumber test I get the error:
Configuring TestNG with: org.apache.maven.surefire.testng.conf.TestNG652Configurator@6d4b1c02
Tests run: 0, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.75 sec

Can you please help me out with this is issue, I would like to use ExtendedCucumberOptions with Junit

**Comment by robintyagi12** [comment]
In case if you are running POM.xml and then getting this error then probably then please checkout this link.https://stackoverflow.com/a/54770032/10567003
I got similar issue when running POM.xml and it shall not be related to extended Cucumber.

**Comment by CucumberUserR** [comment]
thank you, but tried that I still see my job when run on Jenkins has the error

 Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M3:test (default-test) on project tstCucumber: No tests were executed!  (Set -DfailIfNoTests=false to ignore this error.) 

Though tests actually got executed

**Comment by CucumberUserR** [comment]
I was able to resolve my issue by

<plugins>
		<plugin>
			<groupId>org.apache.maven.plugins</groupId>
			<artifactId>maven-surefire-plugin</artifactId>
			<version>3.0.0-M3</version>
<dependencies>
<dependency>
    <groupId>org.apache.maven.surefire</groupId>
    <artifactId>surefire-junit4</artifactId>
    <version>3.0.0-M3</version>
</dependency>

</dependencies>

**Comment by robintyagi12** [comment]
Cool
